config/routes.rb
Rails.application.routes.draw do
  root to: 'schools#index'
  resources :schools
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/school.rb
class School < ApplicationRecord
  validates :name, :address, :country, :state, :city, :state, presence: true
  paginates_per 9
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    if params[:q]
      @schools = School.where("lower(name) LIKE ?", "%#{params[:q].downcase}%").order(:name).page params[:page]
    else
      @schools = School.order(:name).page params[:page]
    end
    
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to schools_url, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to schools_url, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name, :address, :city, :state, :country)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_errors(object, field_name)
    if object.errors.any?
      if object.errors.messages[field_name].present?
        content_tag(:span, object.errors.messages[field_name].join(", "), class: ["w-error"])
      end
    end
  end
  
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolAutocomplete</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-typeahead/2.11.0/jquery.typeahead.min.js"></script>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/jquery-typeahead/2.11.0/jquery.typeahead.min.css'>

  </head>

  <body>
    <nav class="navbar navbar-dark bg-primary box-shadow">
      <a class="navbar-brand" href="/">
        School Management
      </a>
    </nav>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/schools/_form.html.haml
.card.card-primary
  .card-header
    %h3.card-title Details
  
  .card-body
    = form_for school do |f|
      .row
        .col-sm-12
          .form-group
            = f.label 'Name'
            = f.text_field :name, class: "form-control", placeholder: 'Name'
            = show_errors(school, :name)
      .row
        .col-sm-12
          .form-group
            = f.label 'Address'
            = f.text_field :address, class: "form-control", placeholder: 'Address'
            = show_errors(school, :address)

      .row
        .col-sm-6
          .form-group
            = f.label 'City'
            = f.text_field :city, class: "form-control", placeholder: 'City'
            = show_errors(school, :city)    
        .col-sm-6
          .form-group
            = f.label 'State'
            = f.text_field :state, class: "form-control", placeholder: 'State'
            = show_errors(school, :state)
      .row
        .col-sm-6
          .form-group
            = f.label 'Country'
            = f.text_field :country, class: "form-control", placeholder: 'Country'
            = show_errors(school, :country)
      
      
      .card-footer
        = f.submit "Submit", class: 'btn btn-info'

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-12.col-md-3
        %h1 Schools
      .col-sm-12.col-md-7
        %form
          .typeahead__container
            .typeahead__field
              .typeahead__query
                %input.js-typeahead{:autocomplete => "off", :name => "q", value: "#{params[:q]}", placeholder: 'Search here eg: basis'}/
              .typeahead__button
                %button{:type => "submit"}
                  %span.typeahead__search-icon

      .col-sm-2.col-md-2.float-right
        = link_to '+', new_school_path, class: 'btn btn-info btn-circle btn-xl plus box-shadow'

.row
  - @schools.each do |school|
    .col-md-4.col-sm-12.my-card
      .card.box-shadow{:style => "width: 18rem;"}
        .card-body
          %p.card-text= school.name
          = link_to 'Edit', edit_school_path(school)
          = link_to 'Destroy', { action: :destroy, id: school.id }, method: :delete, data: { confirm: 'Are you sure?' }, class: 'l-padding'

.row.my-card
  = paginate @schools, theme: 'twitter-bootstrap-4'


:javascript
  document.addEventListener("turbolinks:load", function() {
    $.typeahead({
        input: ".js-typeahead",
        order: "asc",
        dynamic: true,
        source: {
            groupName: {
              display: "name",
              ajax: function (query) {
                return {
                  url: "/schools",
                  data: { q: "{{query}}" },                  
                }
              }
            }
        }
    });
  });

app/views/schools/new.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1 New School

%section.content
  .container-fluid
    .row
      .col-md-12
        = render 'form', school: @school

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @school.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @school.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @school.country %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>